CREATE
DATABASE IF NOT EXISTS test;
CREATE
DATABASE IF NOT EXISTS dev;
DROP
USER IF EXISTS 'admin'@'%';
CREATE
USER 'admin'@'%' IDENTIFIED BY 'admin1234';
GRANT ALL PRIVILEGES ON test.* TO
'admin'@'%';
GRANT ALL PRIVILEGES ON dev.* TO
'admin'@'%';
FLUSH
PRIVILEGES;
